In [12]:
%pip install statsmodels

Collecting statsmodelsNote: you may need to restart the kernel to use updated packages.

  Downloading statsmodels-0.13.2-cp310-cp310-win_amd64.whl (9.1 MB)
Requirement already satisfied: numpy>=1.17 in c:\users\ndine\appdata\local\programs\python\python310\lib\site-packages (from statsmodels) (1.22.3)
Collecting scipy>=1.3
  Downloading scipy-1.9.1-cp310-cp310-win_amd64.whl (38.6 MB)
Collecting patsy>=0.5.2
  Downloading patsy-0.5.2-py2.py3-none-any.whl (233 kB)
Requirement already satisfied: packaging>=21.3 in c:\users\ndine\appdata\local\programs\python\python310\lib\site-packages (from statsmodels) (21.3)
Requirement already satisfied: pandas>=0.25 in c:\users\ndine\appdata\local\programs\python\python310\lib\site-packages (from statsmodels) (1.4.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\ndine\appdata\local\programs\python\python310\lib\site-packages (from packaging>=21.3->statsmodels) (3.0.8)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\ndine\appdata\local\programs\python\python310\lib\site-packages (from pandas>=0.25->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\ndine\appdata\local\programs\python\python310\lib\site-packages (from pandas>=0.25->statsmodels) (2022.1)
Requirement already satisfied: six in c:\users\ndine\appdata\local\programs\python\python310\lib\site-packages (from patsy>=0.5.2->statsmodels) (1.16.0)
Installing collected packages: scipy, patsy, statsmodels
Successfully installed patsy-0.5.2 scipy-1.9.1 statsmodels-0.13.2

WARNING: You are using pip version 21.2.3; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Users\ndine\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [15]:
import statsmodels.api as sm
import numpy as np
import pandas as pd

In [29]:
mtcars = sm.datasets.get_rdataset('mtcars')
cars = mtcars.data
cars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [31]:
cars_groups = cars.groupby(cars['cyl'])
cars_groups.mean()

,mpg,disp,hp,drat,wt,qsec,vs,am,gear,carb
cyl,,,,,,,,,,
4,26.663636,105.136364,82.636364,4.070909,2.285727,19.137273,0.909091,0.727273,4.090909,1.545455
6,19.742857,183.314286,122.285714,3.585714,3.117143,17.977143,0.571429,0.428571,3.857143,3.428571
8,15.100000,353.100000,209.214286,3.229286,3.999214,16.772143,0.000000,0.142857,3.285714,3.500000